import type { FormlessField, FormlessSchema } from '../types.js';

export function toMarkdownSpec(schema: FormlessSchema): string {
  const visibleFields = schema.fields.filter((field) => !field.hidden);
  const requiredCount = visibleFields.filter((field) => field.required).length;
  const lines: string[] = [
    `# ${schema.title}`,
    '',
    `> Source: ${schema.sourceUrl}`,
    `> Platform: ${formatPlatform(schema.platform)}`,
    `> Parsed: ${schema.parsedAt}`,
    `> Fields: ${visibleFields.length} (${requiredCount} required)`,
    '',
    '---',
    '',
    '## Fields',
    ''
  ];

  visibleFields.forEach((field, index) => {
    lines.push(`### ${index + 1}. ${field.label}${field.required ? ' `required`' : ''}`);
    lines.push(`- **Type:** ${field.type}`);

    if (field.description) {
      lines.push(`- **Description:** ${field.description}`);
    }

    if (field.placeholder) {
      lines.push(`- **Placeholder:** ${field.placeholder}`);
    }

    if (typeof field.minLength === 'number' || typeof field.maxLength === 'number') {
      if (typeof field.minLength === 'number' && typeof field.maxLength === 'number') {
        lines.push(`- **Length:** ${field.minLength} - ${field.maxLength}`);
      } else if (typeof field.minLength === 'number') {
        lines.push(`- **Min length:** ${field.minLength}`);
      } else if (typeof field.maxLength === 'number') {
        lines.push(`- **Max length:** ${field.maxLength}`);
      }
    }

    if (typeof field.min === 'number' || typeof field.max === 'number') {
      if (typeof field.min === 'number' && typeof field.max === 'number') {
        lines.push(`- **Range:** ${field.min} - ${field.max}`);
      } else if (typeof field.min === 'number') {
        lines.push(`- **Minimum:** ${field.min}`);
      } else if (typeof field.max === 'number') {
        lines.push(`- **Maximum:** ${field.max}`);
      }
    }

    if (field.options && field.options.length > 0) {
      lines.push(`- **Options:** ${field.options.join(', ')}`);
    }

    lines.push('');
  });

  lines.push('---');
  lines.push('');
  lines.push('*Generated by [formless](https://github.com/arealigue/formless)*');

  return lines.join('\n');
}

function formatPlatform(platform: FormlessSchema['platform']): string {
  switch (platform) {
    case 'typeform':
      return 'Typeform';
    case 'tally':
      return 'Tally';
    case 'google-forms':
      return 'Google Forms';
    default:
      return 'Unknown';
  }
}

export function summarizeFields(fields: FormlessField[]): { total: number; required: number } {
  const visible = fields.filter((field) => !field.hidden);
  return {
    total: visible.length,
    required: visible.filter((field) => field.required).length
  };
}